version: 2

updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "chip-project/maintainers"
    commit-message:
      prefix: "deps"
      include: "scope"
    
    # Group updates by dependency type
    groups:
      pytorch-ecosystem:
        patterns:
          - "torch*"
          - "torchvision*"
          - "torchaudio*"
      
      scientific-python:
        patterns:
          - "numpy*"
          - "scipy*"
          - "matplotlib*"
          - "h5py*"
      
      development-tools:
        patterns:
          - "pytest*"
          - "black*"
          - "flake8*"
          - "mypy*"
          - "pre-commit*"
      
      documentation:
        patterns:
          - "sphinx*"
          - "myst-parser*"
    
    # Ignore major version updates for critical dependencies
    ignore:
      - dependency-name: "torch*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "numpy*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "astra-toolbox*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "chip-project/maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
